{"name": "test_login_0_failed_wrong_datas[data1]", "status": "passed", "attachments": [{"name": "log", "source": "ebf234f0-069f-4a30-97f4-0689d47a2b73-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '', 'passwd': 'python', 'check': '请输入手机号'}"}], "start": 1608218580070, "stop": 1608218581134, "uuid": "8a92a3c7-874d-4cdd-8415-8e4696f96320", "historyId": "50b62d68a5c78b16f277d604e09ea628", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "39100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}