{"name": "test_login_1_failed_error_data[data0]", "status": "passed", "attachments": [{"name": "log", "source": "ef4c514a-f42d-4206-80be-265de1c12c3f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720559', 'passwd': 'python', 'check': '此账号没有经过授权，请联系管理员!'}"}], "start": 1608217605571, "stop": 1608217606265, "uuid": "efbd28c3-6039-4f31-b591-4712f27e79a0", "historyId": "6a46fcdafac322ca966e3107b2e7a7bd", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "7508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}