{"name": "test_login_1_failed_error_data[data1]", "status": "passed", "attachments": [{"name": "log", "source": "6e3d81e9-d5e0-48c7-9604-9979b0bc819a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'python11', 'check': '帐号或密码错误!'}"}], "start": 1608218585444, "stop": 1608218586557, "uuid": "24d776b7-c77e-4a78-9166-e12610cf3c3c", "historyId": "308aaeb32698655c72872f8225ec1a01", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "39100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}