{"name": "test_login_0_failed_wrong_datas[data0]", "status": "passed", "attachments": [{"name": "log", "source": "48576c1f-c56d-4e1e-826c-7faada4d21ed-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': '', 'check': '请输入密码'}"}], "start": 1608217603826, "stop": 1608217604045, "uuid": "30ed1ba5-ed33-4176-844f-0454126a859c", "historyId": "98ee763b71a2e5d2e8433e177b71f895", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "7508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}