{"name": "test_login_1_failed_error_data[data1]", "status": "passed", "attachments": [{"name": "log", "source": "6725152f-7423-4398-81ae-faa59d2fb4d7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'python11', 'check': '帐号或密码错误!'}"}], "start": 1608217370301, "stop": 1608217371137, "uuid": "2a357e7b-36dc-4dd0-a799-0e0dd5a52357", "historyId": "308aaeb32698655c72872f8225ec1a01", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "56724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}